test:
  override:
    - sudo R -q -e "install.packages(\"devtools\", repos = \"https://cran.rstudio.com/\")"
    - sudo R -q -e "install.packages(\"roxygen2\", repos = \"https://cran.rstudio.com/\")"
    - sudo R -q -e "devtools::install(\"~/mapper\", dependencies=TRUE)"
    - sudo R -q -e "devtools::test(\"~/mapper\")"
